#!/bin/bash
python3 -c 'exec("import os\nW=\"water\"\nS=\"stir.\"\nO=\"bestchol\"\ndef cv(s,b):\n n=0\n for c in s:\n  n=n*len(b)+b.index(c)\n return n\nn=cv(os.environ[\"WATER\"],W)+cv(os.environ[\"STIR\"],S)\nr=\"\"\nwhile n:\n r=O[n%len(O)]+r\n n//=len(O)\nprint(r)")'
