#!/bin/bash
python3 -c 'exec("import os\nW=\"water\"\nS=\"stir.\"\nO=\"bestchol\"\ndef f(s,b):\n n=0\n for c in s:n=n*len(b)+b.index(c)\n return n\nn=f(os.environ[\"WATER\"],W)+f(os.environ[\"STIR\"],S)\nr=\"\"\nwhile n:r=O[n%len(O)]+r;n//=len(O)\nprint(r)")'
