#!/usr/bin/env bash
# This script displays a message and handles signals using a PID file.

echo "$$" > /var/run/myscript.pid

trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid; exit 0' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f /var/run/myscript.pid; exit 0' SIGQUIT

while true
do
    echo "To infinity and beyond"
    sleep 2
done
